name: "Commit Linter"
on: pull_request
jobs:
  lint-commits:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - run: |
          npm install --save-dev @commitlint/cli
          "$(gh pr view ${{ github.event.pull_request.number }} --json commits --jq '.[][0].messageHeadline')" | bash .utils/ci/run_commitlint.sh
