name: "Commit Linter"
on: pull_request
jobs:
  lint-commits:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - run: npm install --save-dev @commitlint/cli
      - run: npx commitlint --from HEAD~1 --to HEAD --verbose --help-url https://github.com/LunarVim/LunarVim/blob/rolling/CONTRIBUTING.md#commit-messages --config .github/workflows/commitlint.config.js
